### ISSUE TITLE
自制的证书如何能够让浏览器自动添加授信？

### ISSUE THREAD

**Issue by andyzheung** [soulteary/certs-maker#11]
如题，对于内部系统来说，自制的证书如何在一个企业内让内部用户都使用，无须浏览器增加授信的过程？

**Comment by soulteary** [comment]
不论何种软件生成的自签名证书，在实际使用过程中，面对的应用场景千变万化，授信过程亦是如此。

可以搜索如何在不同操作系统系统中信任自签名证书，解决你的问题。

你提的问题，不在软件的设计和解决问题的目标中，它是 maker 。

**Comment by andyzheung** [comment]
> 不论何种软件生成的自签名证书，在实际使用过程中，面对的应用场景千变万化，授信过程亦是如此。
> 
> 可以搜索如何在不同操作系统系统中信任自签名证书，解决你的问题。
> 
> 你提的问题，不在软件的设计和解决问题的目标中，它是 maker 。

理解你说的，这个软件不解决这个问题。只是想知道是否有比较简洁和易操作，且用户无感知的授信。
