### ISSUE TITLE
firefox 浏览器不信任自签的 CA 证书

### ISSUE THREAD

**Issue by he-sb** [soulteary/certs-maker#14]
1. 如果 `FOR_K8S` 不配置，那么生成的证书将同时包含了根证书，这种证书即使添加到系统证书中， firefox 也没法信任，始终需要添加安全例外才行（错误代码: MOZILLA_PKIX_ERROR_CA_CERT_USED_AS_END_ENTITY），其他浏览器没有这个限制，可以直接信任系统证书
    - 原因在这里 https://stackoverflow.com/a/59739121 ，简要来说就是 firefox 出于安全原因，不允许信任自签名的根证书同时作为终端证书使用
2. 而如果配置 `FOR_K8S`为 `on` ，那么生成的证书文件只包含终端证书，没有根证书，从而没法导入系统信任

因此能否提供一个选项，将自签后的根证书和终端证书都提供出来
- 也就是将原来的 `example.com.crt` 拆分为两个证书文件提供，一个终端证书，一个根证书，根证书用于添加信任，终端证书用于终端通讯

**Comment by soulteary** [comment]
see https://github.com/soulteary/certs-maker/releases/tag/v3.3.0
