### ISSUE TITLE
环境变量支持自定义证书文件名

### ISSUE THREAD

**Issue by yqs112358** [soulteary/certs-maker#18]
RT，打算将生成自签证书直接挂载进其他容器使用，但是某些服务对证书文件名要求苛刻必须是特定格式，还需要额外跑命令处理感觉不太优雅，希望可以在certs-maker实现自定义名字

**Comment by soulteary** [comment]
@yqs112358 see https://github.com/soulteary/certs-maker/releases/tag/v3.6.1
