### ISSUE TITLE
域名中带有英文减号时无法生成证书

### ISSUE THREAD

**Issue by he-sb** [soulteary/certs-maker#7]
当指定参数 `--CERT_DNS=pve.he-sb.home` ，即运行容器的命令为

```bash
docker run --rm -it -v `pwd`/ssl:/ssl soulteary/certs-maker "--CERT_DNS=pve.he.home"
```

时，会报错：

```bash
running soulteary/certs-maker v2.4.2
wrong domains, set to default value: lab.com,*.lab.com,*.data.lab.com
```

实际生成的是域名为 `lab.com` 的证书

**Comment by he-sb** [comment]
尝试了使用 `-e CERT_DNS="pve.he-sb.home"` ，问题依旧。完整命令：

```bash
docker run --rm -it -v `pwd`/ssl:/ssl -e CERT_DNS="pve.he-sb.home" soulteary/certs-maker
```

**Comment by soulteary** [comment]
感谢反馈，@he-sb 试试看 v2.4.3 版本～

**Comment by he-sb** [comment]
> 

v2.4.3 版本生成的证书域名中，减号前面的部分，包括减号自身，都不见了。。😂

比如命令为

```bash
docker run --rm -it -v `pwd`/ssl:/ssl soulteary/certs-maker "--CERT_DNS=pve.he-sb.home"
```

或

```bash
docker run --rm -it -v `pwd`/ssl:/ssl -e CERT_DNS="pve.he-sb.home" soulteary/certs-maker
```

时，生成的证书文件名均为：

```bash
sb.home.conf  sb.home.crt  sb.home.key
```

**Comment by soulteary** [comment]
> @soulteary
> 
> v2.4.3 版本生成的证书文件名，域名中减号前面的部分，包括减号自身，都不见了。。😂
> 
> 比如命令为
> 
> ```shell
> docker run --rm -it -v `pwd`/ssl:/ssl soulteary/certs-maker "--CERT_DNS=pve.he-sb.home"
> ```
> 
> 或
> 
> ```shell
> docker run --rm -it -v `pwd`/ssl:/ssl -e CERT_DNS="pve.he-sb.home" soulteary/certs-maker
> ```
> 
> 时，生成的证书文件名均为：
> 
> ```shell
> sb.home.conf  sb.home.crt  sb.home.key
> ```
> 
> 证书中的 DNS 属性中的域名是没问题的，确实是 `pve.he-sb.home` 没问题，只有生成的文件名有问题

@he-sb fixed

**Comment by he-sb** [comment]
> > @soulteary
> > v2.4.3 版本生成的证书文件名，域名中减号前面的部分，包括减号自身，都不见了。。😂
> > 比如命令为
> > ```shell
> > docker run --rm -it -v `pwd`/ssl:/ssl soulteary/certs-maker "--CERT_DNS=pve.he-sb.home"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 或
> > ```shell
> > docker run --rm -it -v `pwd`/ssl:/ssl -e CERT_DNS="pve.he-sb.home" soulteary/certs-maker
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 时，生成的证书文件名均为：
> > ```shell
> > sb.home.conf  sb.home.crt  sb.home.key
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 证书中的 DNS 属性中的域名是没问题的，确实是 `pve.he-sb.home` 没问题，只有生成的文件名有问题
> 
> @he-sb fixed

很赞，没问题啦~
